"""add sex and age to user

Revision ID: 0304ad5e0d19
Revises: 3836fcf55060
Create Date: 2024-06-07 09:36:25.697213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0304ad5e0d19'
down_revision = '3836fcf55060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('age')
        batch_op.drop_column('sex')

    # ### end Alembic commands ###
