"""remove created on, updated on for questionnaires

Revision ID: 26e9d6b187f3
Revises: 4e44b20c5de4
Create Date: 2024-05-30 11:49:14.785781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26e9d6b187f3'
down_revision = '4e44b20c5de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaires', schema=None) as batch_op:
        batch_op.drop_column('created_on')
        batch_op.drop_column('updated_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_on', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('created_on', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###
