"""add submissions

Revision ID: 4e44b20c5de4
Revises: 8e0e8cb800c6
Create Date: 2024-05-30 10:30:06.593155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e44b20c5de4'
down_revision = '8e0e8cb800c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_submissions_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('surveys')
    with op.batch_alter_table('questionnaires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_questionnaires_submission_id_submissions'), 'submissions', ['submission_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaires', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_questionnaires_submission_id_submissions'), type_='foreignkey')
        batch_op.drop_column('submission_id')

    op.create_table('surveys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('questionnaire_id', sa.INTEGER(), nullable=True),
    sa.Column('created_on', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_on', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], name='fk_surveys_questionnaire_id_questionnaires'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_surveys_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('submissions')
    # ### end Alembic commands ###
