"""remove user id column from questionnaire

Revision ID: 899f11ff43a3
Revises: 26e9d6b187f3
Create Date: 2024-05-30 12:01:37.977355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899f11ff43a3'
down_revision = '26e9d6b187f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaires', schema=None) as batch_op:
        batch_op.drop_constraint('fk_questionnaires_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_questionnaires_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
